sudo: false
language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - '2.1'
  - '2.2'
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --2.0"
