language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - jruby-19mode
  - rbx
matrix:
  allow_failures:
    - rvm: ruby-head # parser cannot handle it jet per default
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
